import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs';
fs.mkdirSync('build',{recursive:true});
const browser=await chromium.launch({headless:true,args:['--use-angle=swiftshader','--enable-webgl','--ignore-gpu-blocklist']});
const page=await browser.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1});
page.setDefaultTimeout(120000);
const errors=[]; const requests=[];
page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
page.on('pageerror',e=>errors.push(String(e)));
page.on('request',r=>requests.push(r.url()));
try{
 const startedAt=Date.now();
 await page.goto('http://127.0.0.1:8000/index.html',{waitUntil:'domcontentloaded'});
 await page.waitForFunction(()=>window.ALAN_12_1_INSTANCE?.map?.isStyleLoaded?.());
 await page.waitForFunction(()=>document.getElementById('loading')?.hasAttribute('hidden'));
 await page.waitForFunction(()=>window.ALAN_12_1_INSTANCE?.diagnostics?.().imageDrawCalls>0);
 const diagnostics=await page.evaluate(()=>{const i=window.ALAN_12_1_INSTANCE;const d=i.diagnostics();const r=i.map.__mountainImageLayer;const id=i.data.iconBindings[0].point_id;return{...d,status:document.getElementById('map-status')?.textContent||'',bindingPropertyKeys:[...new Set(i.data.iconBindings.flatMap(b=>Object.keys(b||{})))].sort(),widthAt8:r.measureWidth(id,8),widthAt9:r.measureWidth(id,9),canvasWidth:i.map.getCanvas().width,canvasHeight:i.map.getCanvas().height};});
 const external=requests.filter(u=>!u.startsWith('http://127.0.0.1:8000/')&&!u.startsWith('blob:http://127.0.0.1:8000/'));
 const relevant=errors.filter(m=>!/favicon|WebGL performance caveat/i.test(m));
 assert.equal(diagnostics.version,'12.1.2');
 assert.equal(diagnostics.flat,true);
 assert.deepEqual(diagnostics.sourceIds.sort(),['boundary','mountain-points']);
 assert.equal(diagnostics.pointCount,1000);
 assert.equal(diagnostics.iconBindingCount,300);
 assert.equal(diagnostics.imageLayerCount,300);
 assert.equal(diagnostics.imageVertexCount,1800);
 assert.ok(diagnostics.imageDrawCalls>0);
 assert.equal(diagnostics.layerIds.filter(id=>id==='mountain-images').length,1);
 assert.equal(diagnostics.layerIds.some(id=>id.startsWith('mountain-icons-')),false);
 assert.deepEqual(diagnostics.bindingPropertyKeys,['icon_id','icon_scale','min_zoom','point_id','priority']);
 assert.equal(diagnostics.status,'1000 точек · 300 фигурок');
 assert.ok(Math.abs(diagnostics.widthAt9/diagnostics.widthAt8-2)<0.0001);
 assert.equal(external.length,0,`external requests: ${external.join(', ')}`);
 assert.equal(relevant.length,0,`browser errors: ${relevant.join('\n')}`);
 const report={firstUsefulFrameMs:Date.now()-startedAt,diagnostics,externalRequests:external,browserErrors:relevant,requestCount:requests.length};
 fs.writeFileSync('build/12.1-browser-diagnostics.json',JSON.stringify(report,null,2));
 await page.screenshot({path:'build/12.1-map.png',animations:'disabled'});
 console.log(JSON.stringify(report,null,2));
}catch(error){await page.screenshot({path:'build/12.1-map-failed.png',animations:'disabled'}).catch(()=>{});fs.writeFileSync('build/12.1-browser-errors.json',JSON.stringify({error:String(error),errors,requests},null,2));throw error;}finally{await browser.close();}
