(function (root, factory) {
  if (typeof module === 'object' && module.exports) module.exports = factory(require('./config.js'));
  else root.ALAN_12_1_DATA = factory(root.ALAN_12_1_CONFIG);
})(typeof self !== 'undefined' ? self : this, function (config) {
  'use strict';
  const MORPHOLOGY_ORDER = Object.freeze(Object.keys(config.morphologies));
  const ROLE_ORDER = Object.freeze(['main_mountain', 'five_thousander', 'unique_mountain']);
  const ORDINARY_ID_PATTERN = /^(mount|rock|ridge|hill)(-(main|5000))?-\d{4}$/;
  const ICON_PATTERN = /^(rounded_hill|rounded_mountain|steep_mountain|isolated_peak|massif|ridge|rocky_peak|rocky_ridge|plateau)_0[1-4]$/;
  function collectCoordinates(value, output) { if (!Array.isArray(value)) return; if (value.length >= 2 && Number.isFinite(Number(value[0])) && Number.isFinite(Number(value[1]))) { output.push([Number(value[0]), Number(value[1])]); return; } value.forEach((child) => collectCoordinates(child, output)); }
  function calculateBounds(collection) { const coordinates=[]; for(const feature of collection.features||[]) collectCoordinates(feature.geometry?.coordinates,coordinates); if(!coordinates.length) throw new Error('Граница карты не содержит координат.'); return coordinates.reduce((bounds,coordinate)=>[Math.min(bounds[0],coordinate[0]),Math.min(bounds[1],coordinate[1]),Math.max(bounds[2],coordinate[0]),Math.max(bounds[3],coordinate[1])],[Infinity,Infinity,-Infinity,-Infinity]); }
  function normalizeBoundary(collection) { if(!collection||collection.type!=='FeatureCollection'||!Array.isArray(collection.features)) throw new Error('Файл границы имеет неверный формат.'); const features=collection.features.filter((feature)=>['Polygon','MultiPolygon'].includes(feature?.geometry?.type)).map((feature)=>({type:'Feature',properties:{id:'karachay-balkaria-nalsana'},geometry:feature.geometry})); if(!features.length) throw new Error('В файле не найдена рабочая граница.'); return {type:'FeatureCollection',features}; }
  function normalizeRender(collection) { if(!collection||collection.type!=='FeatureCollection'||!Array.isArray(collection.features)) throw new Error('Файл рендера гор имеет неверный формат.'); const ids=new Set(); const counts=Object.fromEntries(MORPHOLOGY_ORDER.map((type)=>[type,0])); const features=collection.features.map((feature)=>{const properties=feature?.properties||{};const coordinates=feature?.geometry?.type==='Point'?feature.geometry.coordinates:null;const id=String(properties.point_id||properties.id||'');const morphology=String(properties.morphology||'');const sourceType=String(properties.source_type||'');const iconId=String(properties.icon_id||'');const longitude=Number(properties.longitude??coordinates?.[0]);const latitude=Number(properties.latitude??coordinates?.[1]);const iconScale=Number(properties.icon_scale);const baseShift=Number(properties.base_shift);const priority=Number(properties.priority);if(!ORDINARY_ID_PATTERN.test(id)||ids.has(id))throw new Error(`Некорректный или повторяющийся ID горного объекта: ${id}`);if(!Object.hasOwn(config.morphologies,morphology))throw new Error(`Неизвестная морфология ${morphology} для ${id}`);if(!['mountain','rock','ridge','hill'].includes(sourceType))throw new Error(`Недопустимый исходный тип ${sourceType} для ${id}`);if(!ICON_PATTERN.test(iconId)||!iconId.startsWith(`${morphology}_`))throw new Error(`Фигурка ${iconId} не соответствует морфологии ${morphology}: ${id}`);if(![longitude,latitude,iconScale,baseShift,priority].every(Number.isFinite)||iconScale<=0||Math.abs(baseShift)>0.2)throw new Error(`Некорректные параметры рендера: ${id}`);ids.add(id);counts[morphology]+=1;return{type:'Feature',properties:{id,point_id:id,source_type:sourceType,morphology,longitude,latitude,elevation_m:properties.elevation_m===null?null:Number(properties.elevation_m),name:String(properties.name||''),icon_id:iconId,icon_scale:iconScale,base_shift:baseShift,priority},geometry:{type:'Point',coordinates:[longitude,latitude]}};});if(features.length!==975)throw new Error(`Ожидалось 975 PNG-фигурок, получено ${features.length}.`);return{collection:{type:'FeatureCollection',features},summary:{total:features.length,counts}}; }
  function normalizeSpecialMountains(collection) { if(!collection||collection.type!=='FeatureCollection'||!Array.isArray(collection.features))throw new Error('Файл особых гор имеет неверный формат.');const ids=new Set();const counts=Object.fromEntries(ROLE_ORDER.map((role)=>[role,0]));const features=collection.features.map((feature)=>{const properties=feature?.properties||{};const coordinates=feature?.geometry?.type==='Point'?feature.geometry.coordinates:null;const id=String(properties.id||'');const role=String(properties.role||'');const name=String(properties.name||'').trim();const longitude=Number(properties.longitude??coordinates?.[0]);const latitude=Number(properties.latitude??coordinates?.[1]);const elevation=Number(properties.elevation_m);const morphology=properties.morphology==null?null:String(properties.morphology);if((!ORDINARY_ID_PATTERN.test(id)&&id!=='mingi_tau')||ids.has(id))throw new Error(`Некорректный или повторяющийся ID особой горы: ${id}`);if(!Object.hasOwn(config.roles,role))throw new Error(`Неизвестная роль ${role}: ${id}`);if(!name||![longitude,latitude,elevation].every(Number.isFinite)||elevation<=0)throw new Error(`Некорректные данные особой горы: ${id}`);if(properties.icon_id!=null)throw new Error(`Особая гора не должна иметь PNG: ${id}`);if(morphology!==null&&!Object.hasOwn(config.morphologies,morphology))throw new Error(`Неизвестная справочная морфология ${morphology}: ${id}`);ids.add(id);counts[role]+=1;return{type:'Feature',properties:{id,role,name,elevation_m:elevation,longitude,latitude,morphology,semantic_note:String(properties.semantic_note||''),source:String(properties.source||'')},geometry:{type:'Point',coordinates:[longitude,latitude]}};});if(features.length!==26)throw new Error(`Ожидалось 26 особых точек, получено ${features.length}.`);if(counts.main_mountain!==21||counts.five_thousander!==4||counts.unique_mountain!==1)throw new Error(`Некорректные роли особых гор: ${JSON.stringify(counts)}`);const mingi=features.filter((feature)=>feature.properties.id==='mingi_tau');if(mingi.length!==1||mingi[0].properties.role!=='unique_mountain'||mingi[0].properties.name!=='Mingi Tau')throw new Error('Mingi Tau должен существовать ровно один раз как unique_mountain.');return{collection:{type:'FeatureCollection',features},summary:{total:features.length,counts}}; }
  function normalizeIconManifest(source) { if(!source||!Array.isArray(source.icons)||!source.atlas)throw new Error('Манифест фигурок имеет неверный формат.');if(String(source.version)!==config.version)throw new Error(`Версия манифеста ${source.version} не совпадает с ${config.version}.`);if(String(source.atlas_format)!=='base64-png')throw new Error('Атлас должен быть base64-png.');const ids=new Set();const categoryCounts=Object.fromEntries(MORPHOLOGY_ORDER.map((category)=>[category,0]));const icons=source.icons.map((icon)=>{const id=String(icon.id||'');const category=String(icon.category||'');const variant=Number(icon.variant);const x=Number(icon.x),y=Number(icon.y),width=Number(icon.width),height=Number(icon.height);if(!ICON_PATTERN.test(id)||ids.has(id)||!Object.hasOwn(config.morphologies,category)||!id.startsWith(`${category}_`)||![1,2,3,4].includes(variant))throw new Error(`Недопустимая или повторяющаяся фигурка: ${id}`);if(![x,y,width,height].every(Number.isFinite)||x<0||y<0||width<=0||height<=0)throw new Error(`Некорректная область фигурки: ${id}`);ids.add(id);categoryCounts[category]+=1;return{id,category,variant,x,y,width,height};});if(icons.length!==36||Object.values(categoryCounts).some((count)=>count!==4))throw new Error(`Манифест должен содержать 9 категорий × 4 варианта: ${JSON.stringify(categoryCounts)}`);return{version:config.version,atlas:String(source.atlas),atlas_format:'base64-png',atlas_width:Number(source.atlas_width),atlas_height:Number(source.atlas_height),pixel_ratio:Number(source.pixel_ratio||1),icons}; }
  function normalizeRivers(source) { if(!source||source.type!=='FeatureCollection'||!Array.isArray(source.features))throw new Error('Файл рек имеет неверный формат.');const ids=new Set();const tiers={1:0,2:0,3:0};const features=source.features.map((feature)=>{const geometry=feature?.geometry;const properties=feature?.properties||{};const systemId=String(properties.system_id||'');const name=String(properties.name_ru||'').trim();const tier=Number(properties.tier);if(!geometry||!['LineString','MultiLineString'].includes(geometry.type)||!systemId||!name||![1,2,3].includes(tier)||ids.has(systemId))throw new Error(`Некорректная речная система: ${systemId||'без ID'}`);ids.add(systemId);tiers[tier]+=1;return{type:'Feature',properties:{system_id:systemId,name_ru:name,tier,width_class:tier===1?'major':tier===2?'medium':'minor'},geometry};});if(features.length!==31)throw new Error(`Ожидалась 31 геометрия речных систем, получено ${features.length}.`);return{collection:{type:'FeatureCollection',features},summary:{features:features.length,representedSystems:32,tiers}}; }
  async function loadCompressedJson(url) { const response=await fetch(`${url}.gz.b64`,{cache:'no-cache'});if(!response.ok)throw new Error(`Не загружен ${url}.gz.b64 (HTTP ${response.status}).`);const encoded=(await response.text()).trim();const binary=atob(encoded);const bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i+=1)bytes[i]=binary.charCodeAt(i);const stream=new Blob([bytes]).stream().pipeThrough(new DecompressionStream('gzip'));return JSON.parse(await new Response(stream).text()); }
  async function loadJson(url) { if(url===config.mountainRenderUrl)return loadCompressedJson(url);const response=await fetch(url,{cache:'no-cache'});if(!response.ok)throw new Error(`Не загружен ${url} (HTTP ${response.status}).`);return response.json(); }
  async function loadStageData() { const [rawBoundary,rawRender,rawSpecialMountains,rawManifest,rawRivers]=await Promise.all([loadJson(config.boundaryUrl),loadJson(config.mountainRenderUrl),loadJson(config.specialMountainsUrl),loadJson(config.iconManifestUrl),loadJson(config.riversUrl)]);const boundary=normalizeBoundary(rawBoundary);const render=normalizeRender(rawRender);const special=normalizeSpecialMountains(rawSpecialMountains);const iconManifest=normalizeIconManifest(rawManifest);const rivers=normalizeRivers(rawRivers);return{boundary,icons:render.collection,specialMountains:special.collection,iconManifest,rivers:rivers.collection,summary:{total:render.summary.total+special.summary.total,pngTotal:render.summary.total,specialTotal:special.summary.total,counts:render.summary.counts,specialCounts:special.summary.counts,rivers:rivers.summary},bounds:calculateBounds(boundary)}; }
  return Object.freeze({MORPHOLOGY_ORDER,ROLE_ORDER,calculateBounds,normalizeBoundary,normalizeRender,normalizeSpecialMountains,normalizeIconManifest,normalizeRivers,loadStageData});
});
